config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "lists#index"
  get "search", to: "lists#search", as: :search

  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: {scope: :list_id}, presence: true
  validates :list_id, presence: true

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
    @movies = Movie.order(title: :asc)
  end

  def create
    @list = List.find(params[:list_id])
    @bookmarks = @list.bookmarks.all
    @newbookmark = Bookmark.new(bookmark_params)
    @newbookmark.list = @list
    if @newbookmark.save
      redirect_to list_path(@newbookmark.list)
    else
      render "lists/show", status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    @list = List.find(params[:id])

    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :list_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]


  def index
    @lists = List.all
  end

  def show
    @bookmarks = @list.bookmarks.all
    @newbookmark = Bookmark.new
    @movies = Movie.order(title: :asc)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
     if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  def search

  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_bookform.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <%= f.association :movie, collection: @movies %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/bookmarks/_form.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/bookmarks/new.html.erb
<div class="container">
    <%= render 'form', list: @list, bookmark: @bookmark%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Watch List" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Rails Watch List">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-black font-color-white px-4">
       <div class="white-icon"><i class="fa-solid fa-clapperboard"></i></div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="dropdown" data-bs-target="#navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to 'Home', lists_path, class:"nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <button class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
              Lists
            </button>
            <ul class="dropdown-menu">
            <% List.all.each do |list| %>
                <li><%= link_to list.name, list_path(list), class:"dropdown-item" %></li>
            <% end %>
            </ul>
          </li>
        </ul>
        <%= simple_form_for :search, url: search_path, method: :get, html: { class: "d-flex" } do |f| %>
          <%= f.input :query,
              label: false,
              input_html: {
                class: "form-control me-2",
                placeholder: "Search..."
              } %>

          <%= f.input :category,
              collection: [["Lists", "list"], ["Movies", "movie"]],
              include_blank: false,
              label: false,
              input_html: { class: "form-select me-2" } %>

          <%= f.button :submit, "Search", class: "btn btn-outline-success" %>

         <% end %>
      </div>
    </nav>

    
    <%= yield %>
  </body>
</html>

app/views/lists/_bookform.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <%= f.association :movie, collection: @movies %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<% randImg = ["https://picsum.photos/seed/alpha/600/400",
  "https://picsum.photos/seed/bravo/600/400",
  "https://picsum.photos/seed/charlie/600/400",
  "https://picsum.photos/seed/delta/600/400",
  "https://picsum.photos/seed/echo/600/400",
  "https://picsum.photos/seed/foxtrot/600/400",
  "https://picsum.photos/seed/golf/600/400",
  "https://picsum.photos/seed/hotel/600/400",
  "https://picsum.photos/seed/india/600/400",
  "https://picsum.photos/seed/juliet/600/400",
  "https://picsum.photos/seed/kilo/600/400",
  "https://picsum.photos/seed/lima/600/400",
  "https://picsum.photos/seed/mike/600/400",
  "https://picsum.photos/seed/november/600/400",
  "https://picsum.photos/seed/oscar/600/400",
  "https://picsum.photos/seed/papa/600/400",
  "https://picsum.photos/seed/quebec/600/400",
  "https://picsum.photos/seed/romeo/600/400",
  "https://picsum.photos/seed/sierra/600/400",
  "https://picsum.photos/seed/tango/600/400",
  "https://picsum.photos/seed/uniform/600/400",
  "https://picsum.photos/seed/victor/600/400",
  "https://picsum.photos/seed/whiskey/600/400",
  "https://picsum.photos/seed/xray/600/400",
  "https://picsum.photos/seed/yankee/600/400",
  "https://picsum.photos/seed/zulu/600/400"] %>


<div class="banner" style="background-image: linear-gradient(rgba(0, 0, 0, 0.39),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZW1wdHklMjB0aGVhdGVyfGVufDB8fDB8fHww);">
    <div class="container">
        <h1>The Movie Shelf</h1>
        <p>Your place to keep tabs on your favourite films</p>
        <%= link_to 'New List', new_list_path, class: "btn btn-flat" %>
    </div>
</div>
<div class="container my-4">
    <div class="cards">
        <% @lists.each do |list| %>
        <% photo = "" %>
        <%  if list.photo.attached? 
                photo = cl_image_path(list.photo.key) 
            elsif list.movies.first
                photo = list.movies.first.poster_url
            else
                photo = randImg.sample
            end %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= photo %>)">
            <%= link_to list.name, list_path(list), class: 'text-white text-decoration-none' %>
        </div>
        <% end %>
    </div>
</div>
 

app/views/lists/new.html.erb
<div class="container">
    <%= render 'form', list: @list %>
</div>

app/views/lists/show.html.erb
<div class="d-flex vw-100 justify-content-between align-items-center bg-black px-3">
    <h1 class="text-white"><%= @list.name %></h1>
</div>
<div class="h-100 p-4 "style="
    background-image: url('https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZW1wdHklMjB0aGVhdGVyfGVufDB8fDB8fHww');
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    background-attachment: fixed;">
    <div class="container" >

    <div>
    <% @bookmarks.each do |bookmark| %>
            <div class="card-product m-1">
                <%= image_tag bookmark.movie.poster_url %>
                <div class="d-flex card-product-infos justify-content-between align-items-center w-100">
                        <div>
                            <h2><%= bookmark.movie.title %></h2>
                            <p><%= bookmark.comment %></p>
                        </div>
                        <div>
                            <%= link_to bookmark_path(bookmark), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"}  do %>
                            <i class="fa-solid fa-circle-xmark text-danger"></i>
                            <% end %>
                        </div>
                </div>
            </div> 
    <% end %>
    </div>
        <div class="d-flex justify-content-between">
            <div class="container border border-1 bg-light bg-opacity-50 p-3">
                <h3>Add New Movie:</h3>
                <%= render 'bookform', list: @list, bookmark: @newbookmark%>
            </div>
            <div>
                <%= link_to 'Delete List', list_path(@list), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger border-rounded" %>
            </div>
        </div>
    </div>

</div>